flask:
  host: "localhost"
  port: 5000

directories:
  source_directory: "/Users/christopherfuchs/git-local/BatchProducts/tests/fixtures/images"
  target_directory: "/Users/christopherfuchs/git-local/BatchProducts/data/incoming_images"
  processed_directory: "/Users/christopherfuchs/git-local/BatchProducts/data/processed_images"

db_path: "/Users/christopherfuchs/git-local/BatchProducts/data/image_classifications.db"

model_path: "/Users/christopherfuchs/git-local/BatchProducts/model/trained_enet_0.onnx"

batch:
  min_images_per_run: 5
  max_images_per_run: 100
